version: "3.3"

services:
  snappymail:
    image: waldner/snappymail:2.29.1-php8.2.10
    container_name: snappymail
    hostname: snappymail
    restart: always
    volumes:
      - ${WEBMAIL_DATA}:/snappymail/data
    ports:
      - ${EXTERNAL_HTTP_PORT:-80}:80
    environment:
      - TZ=${TZ:-UTC}
      - USE_SSL=${USE_SSL:-0}
      - HTTP_AUTH_USER=${HTTP_AUTH_USER:-}
      - HTTP_AUTH_PASS=${HTTP_AUTH_PASS:-}

