name: Build and push image
on:
  push:
    branches: ['master']

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login against the ghcr a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # derive tags from Dockerfile
      - name: Generate image tags
        id: gen_tags
        run: |
          php_version=$(awk '/^FROM php:/{ gsub(/^FROM php:|-.*/, ""); print; exit}' Dockerfile)
          snappymail_version=$(awk '/^ENV SNAPPYMAIL_VERSION=/{ sub(/.*=/, ""); print; exit}' Dockerfile)
          image_name=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          full_version="${snappymail_version}-php${php_version}"
          TAGS="${image_name}:latest,${image_name}:${full_version}"
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT


      # Build and push Docker image with Buildx
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.gen_tags.outputs.tags }}
